#!/usr/bin/python3

import asyncio
import json
import secrets
import traceback

from aiohttp import web, WSMsgType


class ClashServer():

    def __init__(self):
        self.app = web.Application()
        self.app.router.add_get("/clash", self.master_handler)
        self.app.router.add_get("/clash/{session}", self.slave_handler)
        self.sessions = {}

    def run(self):
        web.run_app(self.app)

    async def master_handler(self, request):
        print("master: connected")
        session_ws = web.WebSocketResponse()
        await session_ws.prepare(request)

        session_id = secrets.token_urlsafe(6)
        await session_ws.send_json({"session": session_id})
        self.sessions[session_id] = (session_ws, [])

        while True:
            try:
                msg = await session_ws.receive()
                if msg.type == WSMsgType.CLOSE or msg.type == WSMsgType.CLOSED:
                    break
                elif msg.type == WSMsgType.ERROR:
                    break
                elif msg.type == WSMsgType.TEXT:
                    try:
                        data = json.loads(msg.data)
                    except Exception:
                        print(traceback.format_exc())
                        continue

                    to = None
                    if "header" in data:
                        if "to" in data["header"]:
                            to = data["header"]["to"]
                        del data["header"]

                    if to is not None:
                        if to < len(self.sessions[session_id][1]):
                            await self.send_slave(session_id, data, slave_id=to)
                    else:
                        await self.send_slave(session_id, data)
            except asyncio.CancelledError:
                pass

        print(f"close: master {session_id}")
        try:
            for slave_ws, task in self.sessions[session_id][1]:
                try:
                    task.cancel()
                except Exception:
                    print(traceback.format_exc())
        except Exception:
            print(traceback.format_exc())
        del self.sessions[session_id]

        return session_ws

    async def slave_handler(self, request):
        session_id = request.match_info["session"]
        if session_id not in self.sessions:
            return False
        print(f"slave: connected to session {session_id}")
        slave_ws = web.WebSocketResponse()
        await slave_ws.prepare(request)

        async def handler(slave_id):
            while True:
                try:
                    msg = await slave_ws.receive()
                    if msg.type == WSMsgType.CLOSE or msg.type == WSMsgType.CLOSED:
                        break
                    elif msg.type == WSMsgType.ERROR:
                        break
                    elif msg.type == WSMsgType.TEXT:
                        # print(f"master -> slave: {msg.data}")
                        try:
                            data = json.loads(msg.data)
                        except Exception:
                            print(traceback.format_exc())
                            continue

                        data["header"] = {}
                        data["header"]["from"] = slave_id

                        if not await self.send_master(session_id, data):
                            break

                except asyncio.CancelledError:
                    break

        loop = asyncio.get_event_loop()
        slave_id = len(self.sessions[session_id][1])
        task = loop.create_task(handler(slave_id))
        self.sessions[session_id][1].append((slave_ws, task))

        await task

        print(f"close: slave {session_id} {slave_id}")
        data = {}
        data["header"] = {}
        data["header"]["from"] = slave_id
        data["leave"] = True
        await self.send_master(session_id, data)
        if session_id in self.sessions:
            self.sessions[session_id][1].remove((slave_ws, task))

        return slave_ws

    async def send_master(self, session_id, data):
        if session_id not in self.sessions:
            return False
        try:
            master_ws = self.sessions[session_id][0]
            await master_ws.send_str(json.dumps(data))
        except Exception:
            print(traceback.format_exc())
        return True

    async def send_slave(self, session_id, data, slave_id=None):
        if slave_id is None:
            try:
                for slave_ws, _ in self.sessions[session_id][1]:
                    # print(f"master -> slave: {msg.data}")
                    try:
                        await slave_ws.send_str(json.dumps(data))
                    except Exception:
                        print(traceback.format_exc())
            except Exception:
                print(traceback.format_exc())
        else:
            try:
                await self.sessions[session_id][1][slave_id][0].send_str(json.dumps(data))
            except Exception:
                print(traceback.format_exc())


if __name__ == "__main__":
    clashd = ClashServer()
    clashd.run()
